In [12]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Activation

In [13]:
def plot_history(history):
  # function to plot accuracy vs epoch

  plt.plot(history.history['accuracy'], label='accuracy')
  plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.legend(loc='lower right')

In [14]:
#CNN TO BE USED FOR VALIDATION OF FACE CROPPING METHODS

model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(32, (5,5 ), activation='relu', input_shape=(32, 32, 28)))
model.add(tf.keras.layers.MaxPooling2D((2, 2),strides=2))
model.add(tf.keras.layers.Conv2D(64, (5, 5), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D((2, 2),strides=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(0)) #HIDDEN FULLY CONNECTED LAYER
model.add(tf.keras.layers.Dense(6,activation=tf.nn.softmax))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 32)        22432     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 10, 10, 64)        51264     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
flatten (Flatten)            (None, 1600)              0         
_________________________________________________________________
dense (Dense)                (None, 0)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 6

In [ ]:
#FOR SELECTION OF NUMBER OF NEURONS IN FULLY CONNECTED LAYER, ERROR MEASUREMENT HAS TO BE DONE FOR 4 VALUES : 0,256,512,1024. 
#THE CNN FOR THESE CAN BE OBTAINED BY VARYING THE PARAMETER IN ABOVE MODEL

In [33]:
#code to be completed when preprocessing has been done
#K-FOLD CROSS VALIDATION
n_splits=3 #replace 3 by 10
kf = KFold(n_splits=3,shuffle=True, random_state=None)#put n_splits=10 , we've to do 10 fold cross validation
#replace X by input data and Y by input labels
X=[1,2,3,4,5,6,7,8,9,-1,-2,-3,-4,-5,-6,-7,-8,-9] #replace this by input dataset
Y=[1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0] 
X=np.array(X)
Y=np.array(Y)         #replace this by labels for input dataset , i.e the actual output w.r.t to the input 
k=X.shape[0]
n=k/n_splits
Xtr=np.zeros(int(n*(n_splits-1)))
Ytr=np.zeros(int(n*(n_splits-1)))
Xtst=np.zeros(int(n))
Ytst=np.zeros(int(n))
#Xtr=[]
#Ytr=[]
#Xtst=[]
#Ytst=[]
#X=np.array(X)
#Y=np.array(Y)
for train_index, test_index in kf.split(X):
        #print("TRAIN INDEX:", train_index,'\n', "TEST INDEX:", test_index,'\n')
        #np.array(X)[indices.astype(int)]
        #np.array(Y)[indices.astype(int)]
        X_train, X_test = X[train_index], X[test_index]
        Y_train,Y_test=Y[train_index],Y[test_index]

        #X_train=X_train.tolist()
        #X_test=X_test.tolist()
        #Y_train=Y_train.tolist()
        #Y_test=Y_test.tolist()

        Xtr=np.vstack((Xtr,X_train))
        Ytr=np.vstack((Ytr,Y_train))
        Xtst=np.vstack((Xtst,X_test))
        Ytst=np.vstack((Ytst,Y_test))
        print("randomtexttoseeifloopisworking")

        #this loop will run n_splits times, at this point the training data is stored in Xtr and Ytr. Testing data in Xtst and Ytst
        #later , you can iterate row-wise through Xtr,Ytr for training and Xtst,Ytst for testing the neural network
        #therefore , neural network will be trained n_splits times.
        
        #print(" TR DATA :\n", X_train) 
        #print(" TST DATA:\n", X_test)
        #print("TR LABEL:\n",Y_train)
        #print(" TST LABEL:\n", Y_test)
#this data will be used for the validation



randomtexttoseeifloopisworking
randomtexttoseeifloopisworking
randomtexttoseeifloopisworking


In [34]:
Xtr=np.delete(Xtr,0,axis=0)
Ytr=np.delete(Ytr,0,axis=0)
Xtst=np.delete(Xtst,0,axis=0)
Ytst=np.delete(Ytst,0,axis=0)

In [35]:
print("xtr: \n",Xtr,"\n")
print("ytr: \n",Ytr,"\n")
print("xtst: \n",Xtst,"\n")
print("ytst: \n",Ytst,"\n")

xtr: 
 [[ 1.  2.  3.  4.  5. -1. -2. -3. -5. -6. -7. -8.]
 [ 3.  4.  6.  7.  8.  9. -1. -2. -3. -4. -5. -9.]
 [ 1.  2.  5.  6.  7.  8.  9. -4. -6. -7. -8. -9.]] 

ytr: 
 [[1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]] 

xtst: 
 [[ 6.  7.  8.  9. -4. -9.]
 [ 1.  2.  5. -6. -7. -8.]
 [ 3.  4. -1. -2. -3. -5.]] 

ytst: 
 [[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]] 



In [36]:
Xtr=Xtr.tolist()
Ytr=Ytr.tolist()
Xtst=Xtst.tolist()
Ytst=Ytst.tolist()
#lists are ready now

In [37]:
print("xtr: \n",Xtr,"\n")
print("ytr: \n",Ytr,"\n")
print("xtst: \n",Xtst,"\n")
print("ytst: \n",Ytst,"\n")

xtr: 
 [[1.0, 2.0, 3.0, 4.0, 5.0, -1.0, -2.0, -3.0, -5.0, -6.0, -7.0, -8.0], [3.0, 4.0, 6.0, 7.0, 8.0, 9.0, -1.0, -2.0, -3.0, -4.0, -5.0, -9.0], [1.0, 2.0, 5.0, 6.0, 7.0, 8.0, 9.0, -4.0, -6.0, -7.0, -8.0, -9.0]] 

ytr: 
 [[1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]] 

xtst: 
 [[6.0, 7.0, 8.0, 9.0, -4.0, -9.0], [1.0, 2.0, 5.0, -6.0, -7.0, -8.0], [3.0, 4.0, -1.0, -2.0, -3.0, -5.0]] 

ytst: 
 [[1.0, 1.0, 1.0, 1.0, 0.0, 0.0], [1.0, 1.0, 1.0, 0.0, 0.0, 0.0], [1.0, 1.0, 0.0, 0.0, 0.0, 0.0]] 



In [ ]:
#Now, each row of Xtr and Ytr correspond to the data to be used for training the neural network. The neural network will have to be trained 
#put code for training neural network and checking accuracy here , preferably in a loop
for i in range(n_splits):
  #training data=Xtr[i] and Ytr[i]
  #testing data = Xtst[i]and Ytst[i]
  #put rest of the code here.



  


In [ ]:
#validation for face cropping and random rotation angle can be done only after preprocessing 