In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Activation

In [0]:
def plot_history(history):
  # function to plot accuracy vs epoch

  plt.plot(history.history['accuracy'], label='accuracy')
  plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.legend(loc='lower right')

In [0]:
#CNN TO BE USED FOR VALIDATION OF FACE CROPPING METHODS

model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(32, (5,5 ), activation='relu', input_shape=(32, 32, 28)))
model.add(tf.keras.layers.MaxPooling2D((2, 2),strides=2))
model.add(tf.keras.layers.Conv2D(64, (5, 5), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D((2, 2),strides=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(0)) #HIDDEN FULLY CONNECTED LAYER
model.add(tf.keras.layers.Dense(6,activation=tf.nn.softmax))
model.summary()

In [0]:
#FOR SELECTION OF NUMBER OF NEURONS IN FULLY CONNECTED LAYER, ERROR MEASUREMENT HAS TO BE DONE FOR 4 VALUES : 0,256,512,1024. 
#THE CNN FOR THESE CAN BE OBTAINED BY VARYING THE PARAMETER IN ABOVE MODEL

In [13]:
#code to be completed when preprocessing has been done
#K-FOLD CROSS VALIDATION
kf = KFold(n_splits=2,shuffle=True, random_state=None)
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]]) #to be replaced by input data

for train_index, test_index in kf.split(X):
        print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = X[train_index], X[test_index]
        print(" tr data :\n", X_train) 
        print(" tst data:\n", X_test)
#this data will be used for the validation



TRAIN: [2 3] TEST: [0 1]
 tr data :
 [[5 6]
 [7 8]]
 tst data:
 [[1 2]
 [3 4]]
TRAIN: [0 1] TEST: [2 3]
 tr data :
 [[1 2]
 [3 4]]
 tst data:
 [[5 6]
 [7 8]]


In [0]:
#model.compile(optimizer = tf.keras.optimizers.momentum (lr=lr),loss = 'sparse_categorical_crossentropy',metrics=['accuracy'])
#history = model.fit(x_train, y_train, epochs=10,validation_data=(x_test, y_test))
#plot_history(history)
#to be done for all 4 values of neurons of fully connected layer and face cropping methods